-- MySQL Script generated by MySQL Workbench
-- Wed Nov  1 01:55:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fast-foodies
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fast-foodies` ;

-- -----------------------------------------------------
-- Schema fast-foodies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fast-foodies` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fast-foodies` ;

-- -----------------------------------------------------
-- Table `fast-foodies`.`burgers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`burgers` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`burgers` (
  `lettuce` TINYINT(1) NULL,
  `FK_Food_Number` INT NOT NULL,
  `ketchup` TINYINT(1) NULL,
  `mayonaise` TINYINT(1) NULL,
  `mustard` TINYINT(1) NULL,
  `onions` TINYINT(1) NULL,
  `tomatoes` TINYINT(1) NULL,
  PRIMARY KEY (`FK_Food_Number`),
  CONSTRAINT `FK_Burger-Food`
    FOREIGN KEY (`FK_Food_Number`)
    REFERENCES `fast-foodies`.`food` (`Food_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`cook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`cook` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`cook` (
  `FK_Employee_ID` INT NOT NULL,
  `frying_pan` VARCHAR(45) NULL,
  PRIMARY KEY (`FK_Employee_ID`),
  CONSTRAINT `FK_Cook_ID`
    FOREIGN KEY (`FK_Employee_ID`)
    REFERENCES `fast-foodies`.`employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`customer` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`customer` (
  `Name` VARCHAR(32) NOT NULL,
  `Cell Number` INT(10) NOT NULL,
  `FK_Employee_ID` INT NULL,
  PRIMARY KEY (`Name`, `Cell Number`),
  INDEX `FK_Employee_ID_idx` (`FK_Employee_ID` ASC) VISIBLE,
  CONSTRAINT `FK_Customer-Employee`
    FOREIGN KEY (`FK_Employee_ID`)
    REFERENCES `fast-foodies`.`employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`drinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`drinks` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`drinks` (
  `size` VARCHAR(8) NULL,
  `Drink_Number` INT NOT NULL,
  `Price` FLOAT NULL,
  `Name` VARCHAR(32) NULL,
  `FK_Order_Number` INT NULL,
  PRIMARY KEY (`Drink_Number`),
  INDEX `FK_Order_Number_idx` (`FK_Order_Number` ASC) VISIBLE,
  CONSTRAINT `FK_Drink-Order`
    FOREIGN KEY (`FK_Order_Number`)
    REFERENCES `fast-foodies`.`meal_order` (`Order_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`employee` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`employee` (
  `Employ_Date` DATE NULL DEFAULT NULL,
  `Salary` FLOAT NULL DEFAULT NULL,
  `Employee_ID` INT NOT NULL,
  PRIMARY KEY (`Employee_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast-foodies`.`food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`food` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`food` (
  `Food_Number` INT NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Price` FLOAT NULL DEFAULT NULL,
  `Expiration_Date` DATE NULL DEFAULT NULL,
  `FK_Employee_ID` INT NULL DEFAULT NULL,
  `FK_Order_Number` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Food_Number`),
  INDEX `FK_Employee_ID_idx` (`FK_Employee_ID` ASC) VISIBLE,
  INDEX `FK_Order_Number_idx` (`FK_Order_Number` ASC) VISIBLE,
  CONSTRAINT `FK_Food-Employee`
    FOREIGN KEY (`FK_Employee_ID`)
    REFERENCES `fast-foodies`.`employee` (`Employee_ID`),
  CONSTRAINT `FK_Food-Order`
    FOREIGN KEY (`FK_Order_Number`)
    REFERENCES `fast-foodies`.`meal_order` (`Order_Number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast-foodies`.`fries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`fries` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`fries` (
  `FK_Food_Number` INT NOT NULL,
  `size` VARCHAR(8) NULL,
  `style` VARCHAR(16) NULL,
  `salt` TINYINT(1) NULL,
  PRIMARY KEY (`FK_Food_Number`),
  CONSTRAINT `FK_Fries-Food`
    FOREIGN KEY (`FK_Food_Number`)
    REFERENCES `fast-foodies`.`food` (`Food_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`front_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`front_staff` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`front_staff` (
  `FK_Employee_ID` INT NOT NULL,
  `position` VARCHAR(32) NULL,
  `FK_Manager_ID` INT NULL,
  PRIMARY KEY (`FK_Employee_ID`),
  INDEX `FK_Manager_ID_idx` (`FK_Manager_ID` ASC) VISIBLE,
  CONSTRAINT `FK_FrontStaff-Employee`
    FOREIGN KEY (`FK_Employee_ID`)
    REFERENCES `fast-foodies`.`employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FrontStaff-Manager`
    FOREIGN KEY (`FK_Manager_ID`)
    REFERENCES `fast-foodies`.`manager` (`FK_Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`manager` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`manager` (
  `Keys` VARCHAR(16) NULL,
  `FK_Employee_ID` INT NOT NULL,
  PRIMARY KEY (`FK_Employee_ID`),
  CONSTRAINT `FK_Manager-Employee`
    FOREIGN KEY (`FK_Employee_ID`)
    REFERENCES `fast-foodies`.`employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`meal_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`meal_order` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`meal_order` (
  `Payment_Type` VARCHAR(32) NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Order_Number` INT NOT NULL,
  `FK_Employee_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Order_Number`),
  INDEX `FK_Employee_ID_idx` (`FK_Employee_ID` ASC) VISIBLE,
  CONSTRAINT `FK_Order-Employee`
    FOREIGN KEY (`FK_Employee_ID`)
    REFERENCES `fast-foodies`.`employee` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast-foodies`.`receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`receipt` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`receipt` (
  `Format` VARCHAR(16) NULL,
  `FK_Order_Number` INT NOT NULL,
  PRIMARY KEY (`FK_Order_Number`),
  CONSTRAINT `FK_Receipt-Order`
    FOREIGN KEY (`FK_Order_Number`)
    REFERENCES `fast-foodies`.`meal_order` (`Order_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`salads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`salads` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`salads` (
  `FK_Food_Number` INT NOT NULL,
  `dressing` TINYINT(1) NULL,
  `size` VARCHAR(8) NULL,
  PRIMARY KEY (`FK_Food_Number`),
  CONSTRAINT `FK_Salad-Food`
    FOREIGN KEY (`FK_Food_Number`)
    REFERENCES `fast-foodies`.`food` (`Food_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`shakes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`shakes` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`shakes` (
  `flavor` VARCHAR(12) NULL,
  `FK_Drink_Number` INT NOT NULL,
  PRIMARY KEY (`FK_Drink_Number`),
  CONSTRAINT `FK_Shake-Drink`
    FOREIGN KEY (`FK_Drink_Number`)
    REFERENCES `fast-foodies`.`drinks` (`Drink_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`sodas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`sodas` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`sodas` (
  `FK_Drink_Number` INT NOT NULL,
  `brand` VARCHAR(12) NULL,
  PRIMARY KEY (`FK_Drink_Number`),
  CONSTRAINT `FK_Soda-Drink`
    FOREIGN KEY (`FK_Drink_Number`)
    REFERENCES `fast-foodies`.`drinks` (`Drink_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast-foodies`.`tea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast-foodies`.`tea` ;

CREATE TABLE IF NOT EXISTS `fast-foodies`.`tea` (
  `FK_Drink_Number` INT NOT NULL,
  `type` VARCHAR(12) NULL,
  PRIMARY KEY (`FK_Drink_Number`),
  CONSTRAINT `FK_Tea-Drink`
    FOREIGN KEY (`FK_Drink_Number`)
    REFERENCES `fast-foodies`.`drinks` (`Drink_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
